speedy – SPEEDY.f90
speedy Program
Sam Hatfield, Fred Kucharski, Franco Molteni
29/04/2019
27 statements
Source File
Uses
params
date
shortwave_radiation
input_output
coupler
initialization
time_stepping
diagnostics
prognostics
forcing
The top-level program. Here we initialize the model and run the main loop until the (continually updated) model datetime (model_datetime) equals the final datetime (end_datetime).
Calls
Contents
Variables
model_step
Variables
Type Attributes Name Initial
integer :: model_step = 1
Call graph
speedy calls datetime_equal, initialize, step, set_forcing, newdate, couple_sea_land
initialize calls set_forcing, initialize_date, initialize_geopotential, print_speedy_title, first_step, initialize_params, initialize_boundaries, initialize_spectral, initialize_physics, initialize_geometry, initialize_prognostics, initialize_coupler, initialize_horizontal_diffusion
step calls step_field_3d, step_field_2d, do_horizontal_diffusion, get_tendencies
set_forcing calls get_qsat, set_orog_land_sfc_drag, radset, setgam, get_zonal_average_fields, grid_to_spec
newdate calls float
couple_sea_land calls couple_land_atm, couple_sea_atm
initialize_date calls float
couple_land_atm calls run_land_model, forint, forin5
couple_sea_atm calls run_sea_model, forint, forin5
first_step calls step, initialize_implicit
get_zonal_average_fields calls solar
initialize_boundaries calls spectral_truncation, load_boundary_file
step_field_3d calls step_field_2d
initialize_spectral calls float, initialize_fourier, initialize_legendre
step_field_2d calls trunct
grid_to_spec calls fourier_dir, legendre_dir
initialize_prognostics calls initialize_from_rest_state
initialize_coupler calls couple_land_atm, couple_sea_atm, sea_model_init, land_model_init
initialize_horizontal_diffusion calls float
do_horizontal_diffusion calls do_horizontal_diffusion_3d, do_horizontal_diffusion_2d
get_tendencies calls get_grid_point_tendencies, implicit_terms, get_spectral_tendencies
get_grid_point_tendencies calls grid_to_spec, laplacian, get_geopotential, spec_to_grid
initialize_implicit calls float
spectral_truncation calls grid_to_spec, spec_to_grid
do_horizontal_diffusion_3d calls do_horizontal_diffusion_2d
fourier_dir calls float, rfftf1
sea_model_init calls load_boundary_file, forchk
initialize_fourier calls rffti1
initialize_from_rest_state calls grid_to_spec, output
load_boundary_file calls load_boundary_file_one_month_from_long, load_boundary_file_2d, load_boundary_file_one_month_from_year
get_spectral_tendencies calls laplacian, get_geopotential
initialize_legendre calls float, get_weights, get_legendre_poly
land_model_init calls load_boundary_file, forchk
load_boundary_file_one_month_from_long calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
load_boundary_file_2d calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
get_legendre_poly calls float
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
output calls spec_to_grid, nf90_enddef, nf90_close, nf90_create, nf90_put_att, nf90_def_dim, nf90_put_var, nf90_def_var
spec_to_grid calls legendre_inv, fourier_inv
fourier_inv calls rfftb1