couple_land_atm – SPEEDY.f90
couple_land_atm Subroutine
21 statements
Source File
public subroutine couple_land_atm(day)
Uses
date
interpolation
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: day
Calls
Called by
Contents
None
Call graph
couple_land_atm calls forint, run_land_model, forin5
initialize_coupler calls couple_land_atm
couple_sea_land calls couple_land_atm
speedy calls couple_sea_land, initialize
initialize calls initialize_coupler