couple_sea_land – SPEEDY.f90
couple_sea_land Subroutine
7 statements
Source File
public subroutine couple_sea_land(day)
Uses
land_model
sea_model
Exchange fluxes between atmosphere and land/sea.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: day
The current day of the model integration (starting from 0)
Calls
Called by
Contents
None
Call graph
couple_sea_land calls couple_land_atm, couple_sea_atm
couple_land_atm calls forin5, forint, run_land_model
couple_sea_atm calls forin5, forint, run_sea_model
speedy calls couple_sea_land