first_step – SPEEDY.f90
first_step Subroutine
8 statements
Source File
public subroutine first_step()
Uses
implicit
Arguments
None
Calls
Called by
Contents
None
Call graph
first_step calls initialize_implicit, step
initialize_implicit calls float
step calls do_horizontal_diffusion, step_field_3d, step_field_2d, get_tendencies
do_horizontal_diffusion calls do_horizontal_diffusion_2d, do_horizontal_diffusion_3d
step_field_3d calls step_field_2d
step_field_2d calls trunct
get_tendencies calls get_spectral_tendencies, get_grid_point_tendencies, implicit_terms
get_spectral_tendencies calls get_geopotential, laplacian
get_grid_point_tendencies calls grid_to_spec, get_geopotential, laplacian, spec_to_grid
do_horizontal_diffusion_3d calls do_horizontal_diffusion_2d
grid_to_spec calls fourier_dir, legendre_dir
spec_to_grid calls fourier_inv, legendre_inv
fourier_dir calls float, rfftf1
fourier_inv calls rfftb1
initialize calls first_step
speedy calls initialize