forchk – SPEEDY.f90
forchk Subroutine
23 statements
Source File
public subroutine forchk(fmask, nf, fmin, fmax, fset, field)
Check consistency of surface fields with land-sea mask and set undefined values to a constant (to avoid over/underflow).
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: fmask(ix,il)
The fractional land-sea mask
integer, intent(in) :: nf
The number of input 2D fields
real, intent(in) :: fmin
The minimum allowable value
real, intent(in) :: fmax
The maximum allowable value
real, intent(in) :: fset
Replacement for undefined values
real, intent(inout) :: field(ix,il,nf)
The output field
Called by
Contents
None
Call graph
sea_model_init calls forchk
land_model_init calls forchk
initialize_coupler calls sea_model_init, land_model_init
initialize calls initialize_coupler
speedy calls initialize