forin5 – SPEEDY.f90
forin5 Subroutine
25 statements
Source File
public subroutine forin5(imon, for12, for1)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: imon
real, intent(in) :: for12(ix*il,12)
real, intent(inout) :: for1(ix*il)
Called by
Contents
None
Call graph
couple_sea_atm calls forin5
couple_land_atm calls forin5
initialize_coupler calls couple_sea_atm, couple_land_atm
couple_sea_land calls couple_sea_atm, couple_land_atm
speedy calls couple_sea_land, initialize
initialize calls initialize_coupler