gen_sppt – SPEEDY.f90
gen_sppt Function
33 statements
Source File
public function gen_sppt() result(sppt_grid)
Uses
spectral
physical_constants
Generate grid point space SPPT pattern distribution.
Arguments
None
Return Value real (ix,il,kx)
The generated grid point pattern
Calls
Called by
Contents
None
Call graph
gen_sppt calls spec_to_grid, randn
spec_to_grid calls fourier_inv, legendre_inv
fourier_inv calls rfftb1
get_physical_tendencies calls gen_sppt