get_grid_point_tendencies – SPEEDY.f90
get_grid_point_tendencies Subroutine
104 statements
Source File
private subroutine get_grid_point_tendencies(vordt, divdt, tdt, psdt, trdt, j1, j2)
Uses
prognostics
physical_constants
geometry
implicit
geopotential
physics
spectral
Arguments
Type Intent Optional Attributes Name
complex, intent(inout), dimension(mx,nx,kx) :: vordt
complex, intent(inout), dimension(mx,nx,kx) :: divdt
complex, intent(inout), dimension(mx,nx,kx) :: tdt
complex, intent(inout) :: psdt(mx,nx)
complex, intent(inout) :: trdt(mx,nx,kx,ntr)
integer, intent(in) :: j1
integer, intent(in) :: j2
Calls
Called by
Contents
None
Call graph
get_grid_point_tendencies calls spec_to_grid, grid_to_spec, get_geopotential, laplacian
spec_to_grid calls fourier_inv, legendre_inv
grid_to_spec calls fourier_dir, legendre_dir
fourier_dir calls rfftf1, float
fourier_inv calls rfftb1
get_tendencies calls get_grid_point_tendencies
step calls get_tendencies
speedy calls step, initialize
first_step calls step
initialize calls first_step