get_tendencies – SPEEDY.f90
get_tendencies Subroutine
13 statements
Source File
public subroutine get_tendencies(vordt, divdt, tdt, psdt, trdt, j2)
Uses
implicit
Arguments
Type Intent Optional Attributes Name
complex, intent(inout), dimension(mx,nx,kx) :: vordt
complex, intent(inout), dimension(mx,nx,kx) :: divdt
complex, intent(inout), dimension(mx,nx,kx) :: tdt
complex, intent(inout) :: psdt(mx,nx)
complex, intent(inout) :: trdt(mx,nx,kx,ntr)
integer, intent(in) :: j2
Calls
Called by
Contents
None
Call graph
get_tendencies calls implicit_terms, get_spectral_tendencies, get_grid_point_tendencies
get_spectral_tendencies calls get_geopotential, laplacian
get_grid_point_tendencies calls grid_to_spec, get_geopotential, laplacian, spec_to_grid
grid_to_spec calls fourier_dir, legendre_dir
spec_to_grid calls fourier_inv, legendre_inv
fourier_dir calls rfftf1, float
fourier_inv calls rfftb1
step calls get_tendencies
speedy calls step, initialize
first_step calls step
initialize calls first_step