get_qsat – SPEEDY.f90
get_qsat Function
28 statements
Source File
public function get_qsat(ta, ps, sig) result(qsat)
Computes saturation specific humidity.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: ta(ix,il)
Absolute temperature
real, intent(in) :: ps(ix,il)
Normalized pressure (p/1000 hPa)
real, intent(in) :: sig
Sigma level
Return Value real (ix,il)
Saturation specific humidity in g/kg
Called by
Contents
None
Call graph
set_forcing calls get_qsat
spec_hum_to_rel_hum calls get_qsat
get_surface_fluxes calls get_qsat
rel_hum_to_spec_hum calls get_qsat
speedy calls set_forcing, initialize
get_physical_tendencies calls get_surface_fluxes
initialize calls set_forcing