get_geopotential – SPEEDY.f90
get_geopotential Function
16 statements
Source File
public function get_geopotential(t, phis) result(phi)
Uses
geometry
Computes spectral geopotential from spectral temperature T and spectral topography phis, as in GFDL Climate Group GCM.
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: t(mx,nx,kx)
Spectral temperature
complex, intent(in) :: phis(mx,nx)
Spectral surface geopotential
Return Value complex (mx,nx,kx)
Spectral geopotential
Called by
Contents
None
Call graph
get_spectral_tendencies calls get_geopotential
get_grid_point_tendencies calls get_geopotential
get_tendencies calls get_spectral_tendencies, get_grid_point_tendencies
step calls get_tendencies
speedy calls step, initialize
first_step calls step
initialize calls first_step