get_spectral_tendencies – SPEEDY.f90
get_spectral_tendencies Subroutine
35 statements
Source File
private subroutine get_spectral_tendencies(divdt, tdt, psdt, j2)
Uses
prognostics
physical_constants
geometry
geopotential
implicit
spectral
Arguments
Type Intent Optional Attributes Name
complex, intent(inout) :: divdt(mx,nx,kx)
complex, intent(inout) :: tdt(mx,nx,kx)
complex, intent(inout) :: psdt(mx,nx)
integer, intent(in) :: j2
Calls
Called by
Contents
None
Call graph
get_spectral_tendencies calls get_geopotential, laplacian
get_tendencies calls get_spectral_tendencies
step calls get_tendencies
speedy calls step, initialize
first_step calls step
initialize calls first_step