get_physical_tendencies – SPEEDY.f90
get_physical_tendencies Subroutine
106 statements
Source File
public subroutine get_physical_tendencies(vor, div, t, q, phi, psl, utend, vtend, ttend, qtend)
Uses
auxiliaries
physical_constants
geometry
boundaries
land_model
sea_model
sppt
convection
large_scale_condensation
shortwave_radiation
longwave_radiation
surface_fluxes
vertical_diffusion
humidity
spectral
Compute physical parametrization tendencies for u, v, t, q and add them to the dynamical grid-point tendencies
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: vor(mx,nx,kx)
Vorticity
complex, intent(in) :: div(mx,nx,kx)
Divergence
complex, intent(in) :: t(mx,nx,kx)
Temperature
complex, intent(in) :: q(mx,nx,kx)
Specific Humidity
complex, intent(in) :: phi(mx,nx,kx)
Geopotential
complex, intent(in) :: psl(mx,nx)
ln(Surface pressure)
real, intent(inout) :: utend(ix,il,kx)
Zonal velocity tendency
real, intent(inout) :: vtend(ix,il,kx)
Meridional velocity tendency
real, intent(inout) :: ttend(ix,il,kx)
Temperature tendency
real, intent(inout) :: qtend(ix,il,kx)
Specific humidity tendency
Calls
Contents
None
Call graph
get_physical_tendencies calls get_shortwave_rad_fluxes, get_downward_longwave_rad_fluxes, float, gen_sppt, get_convection_tendencies, get_large_scale_condensation_tendencies, get_surface_fluxes, clouds, get_vertical_diffusion_tend, spec_to_grid
gen_sppt calls spec_to_grid, randn
get_convection_tendencies calls diagnose_convection
get_surface_fluxes calls get_qsat
spec_to_grid calls legendre_inv, fourier_inv
fourier_inv calls rfftb1