grid_to_spec – SPEEDY.f90
grid_to_spec Function
9 statements
Source File
public function grid_to_spec(vorg) result(vorm)
Uses
legendre
fourier
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: vorg(ix,il)
Return Value complex (mx,nx)
Calls
Called by
Contents
None
Call graph
grid_to_spec calls fourier_dir, legendre_dir
fourier_dir calls rfftf1, float
set_forcing calls grid_to_spec
spectral_truncation calls grid_to_spec
initialize_from_rest_state calls grid_to_spec
vdspec calls grid_to_spec
get_grid_point_tendencies calls grid_to_spec
initialize_prognostics calls initialize_from_rest_state
initialize calls set_forcing, initialize_prognostics, initialize_boundaries, first_step
initialize_boundaries calls spectral_truncation
speedy calls set_forcing, initialize, step
get_tendencies calls get_grid_point_tendencies
step calls get_tendencies
first_step calls step