initialize_coupler – SPEEDY.f90
initialize_coupler Subroutine
8 statements
Source File
public subroutine initialize_coupler()
Uses
land_model
sea_model
Initialize both land and sea models.
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize_coupler calls couple_land_atm, land_model_init, couple_sea_atm, sea_model_init
couple_land_atm calls run_land_model, forint, forin5
land_model_init calls load_boundary_file, forchk
couple_sea_atm calls forint, run_sea_model, forin5
sea_model_init calls load_boundary_file, forchk
load_boundary_file calls load_boundary_file_2d, load_boundary_file_one_month_from_year, load_boundary_file_one_month_from_long
load_boundary_file_2d calls nf90_inq_varid, nf90_get_var, nf90_open, nf90_close
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_get_var, nf90_open, nf90_close
load_boundary_file_one_month_from_long calls nf90_inq_varid, nf90_get_var, nf90_open, nf90_close
initialize calls initialize_coupler
speedy calls initialize