initialize_legendre – SPEEDY.f90
initialize_legendre Subroutine
40 statements
Source File
public subroutine initialize_legendre()
Uses
physical_constants
Initializes Legendre transforms and constants used for other subroutines that manipulate spherical harmonics.
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize_legendre calls get_weights, get_legendre_poly, float
get_legendre_poly calls float
initialize_spectral calls initialize_legendre
initialize calls initialize_spectral
speedy calls initialize