initialize_spectral – SPEEDY.f90
initialize_spectral Subroutine
46 statements
Source File
public subroutine initialize_spectral()
Uses
physical_constants
fourier
legendre
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize_spectral calls initialize_legendre, float, initialize_fourier
initialize_legendre calls float, get_weights, get_legendre_poly
initialize_fourier calls rffti1
get_legendre_poly calls float
initialize calls initialize_spectral
speedy calls initialize