initialize_from_rest_state – SPEEDY.f90
initialize_from_rest_state Subroutine
56 statements
Source File
private subroutine initialize_from_rest_state()
Uses
dynamical_constants
physical_constants
geometry
boundaries
diagnostics
spectral
input_output
Initializes all spectral variables starting from a reference atmosphere.
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize_from_rest_state calls grid_to_spec, output
grid_to_spec calls legendre_dir, fourier_dir
output calls nf90_put_att, nf90_enddef, nf90_put_var, nf90_create, nf90_def_dim, spec_to_grid, nf90_close, nf90_def_var
fourier_dir calls rfftf1, float
spec_to_grid calls fourier_inv, legendre_inv
fourier_inv calls rfftb1
initialize_prognostics calls initialize_from_rest_state
initialize calls initialize_prognostics
speedy calls initialize