initialize – SPEEDY.f90
initialize Subroutine
31 statements
Source File
public subroutine initialize()
Uses
params
date
coupler
sea_model
geometry
spectral
geopotential
horizontal_diffusion
physics
input_output
time_stepping
boundaries
prognostics
forcing
Initializes everything.
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize calls initialize_date, initialize_coupler, initialize_horizontal_diffusion, set_forcing, initialize_geopotential, initialize_spectral, print_speedy_title, first_step, initialize_params, initialize_physics, initialize_geometry, initialize_prognostics, initialize_boundaries
initialize_date calls float
initialize_coupler calls sea_model_init, couple_sea_atm, couple_land_atm, land_model_init
initialize_horizontal_diffusion calls float
set_forcing calls get_qsat, set_orog_land_sfc_drag, radset, setgam, get_zonal_average_fields, grid_to_spec
initialize_spectral calls initialize_fourier, initialize_legendre, float
first_step calls step, initialize_implicit
initialize_prognostics calls initialize_from_rest_state
initialize_boundaries calls spectral_truncation, load_boundary_file
initialize_fourier calls rffti1
step calls step_field_3d, do_horizontal_diffusion, get_tendencies, step_field_2d
sea_model_init calls load_boundary_file, forchk
couple_sea_atm calls forint, forin5, run_sea_model
couple_land_atm calls run_land_model, forint, forin5
initialize_from_rest_state calls grid_to_spec, output
initialize_implicit calls float
spectral_truncation calls grid_to_spec, spec_to_grid
land_model_init calls load_boundary_file, forchk
load_boundary_file calls load_boundary_file_one_month_from_long, load_boundary_file_2d, load_boundary_file_one_month_from_year
get_zonal_average_fields calls solar
grid_to_spec calls legendre_dir, fourier_dir
initialize_legendre calls float, get_weights, get_legendre_poly
output calls spec_to_grid, nf90_enddef, nf90_close, nf90_create, nf90_put_att, nf90_def_dim, nf90_put_var, nf90_def_var
load_boundary_file_one_month_from_long calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
load_boundary_file_2d calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
fourier_dir calls float, rfftf1
step_field_3d calls step_field_2d
do_horizontal_diffusion calls do_horizontal_diffusion_2d, do_horizontal_diffusion_3d
get_tendencies calls get_grid_point_tendencies, get_spectral_tendencies, implicit_terms
get_legendre_poly calls float
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
step_field_2d calls trunct
spec_to_grid calls legendre_inv, fourier_inv
get_grid_point_tendencies calls grid_to_spec, spec_to_grid, get_geopotential, laplacian
fourier_inv calls rfftb1
get_spectral_tendencies calls get_geopotential, laplacian
do_horizontal_diffusion_3d calls do_horizontal_diffusion_2d
speedy calls initialize