initialize_horizontal_diffusion – SPEEDY.f90
initialize_horizontal_diffusion Subroutine
32 statements
Source File
public subroutine initialize_horizontal_diffusion()
Uses
dynamical_constants
physical_constants
geometry
Initializes the arrays used for horizontal diffusion.
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize_horizontal_diffusion calls float
initialize calls initialize_horizontal_diffusion
speedy calls initialize