initialize_implicit – SPEEDY.f90
initialize_implicit Subroutine
99 statements
Source File
public subroutine initialize_implicit(dt)
Uses
dynamical_constants
physical_constants
geometry
horizontal_diffusion
matrix_inversion
Initialize constants for implicit computation of horizontal diffusion and gravity waves.
Initialize_implicit initializes constants for the implicit gravity wave computation. It is assumed that that all implicit steps are of length 2*delt and use the forward/backward parameter alph. initialize_implicit has to be re-called whenever either of these two parameters is changed. initialize_implicit should be called even if the explicit option is chosen for the gravity wave terms (the reference state temperature tref is subtracted from some terms anyway to reduce roundoff error; also the constants needed for the biharmonic diffusion, which is assumed always to be backwards implicit, are defined in initialize_implicit).
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: dt
Time step
Calls
Called by
Contents
None
Call graph
initialize_implicit calls float
first_step calls initialize_implicit
initialize calls first_step
speedy calls initialize