initialize_boundaries – SPEEDY.f90
initialize_boundaries Subroutine
8 statements
Source File
public subroutine initialize_boundaries()
Uses
physical_constants
input_output
Initialize boundary conditions (land-sea mask, surface geopotential and surface albedo).
Arguments
None
Calls
Called by
Contents
None
Call graph
initialize_boundaries calls spectral_truncation, load_boundary_file
spectral_truncation calls grid_to_spec, spec_to_grid
load_boundary_file calls load_boundary_file_one_month_from_year, load_boundary_file_one_month_from_long, load_boundary_file_2d
load_boundary_file_one_month_from_year calls nf90_close, nf90_open, nf90_get_var, nf90_inq_varid
grid_to_spec calls fourier_dir, legendre_dir
load_boundary_file_one_month_from_long calls nf90_close, nf90_open, nf90_get_var, nf90_inq_varid
spec_to_grid calls fourier_inv, legendre_inv
load_boundary_file_2d calls nf90_close, nf90_open, nf90_get_var, nf90_inq_varid
fourier_dir calls rfftf1, float
fourier_inv calls rfftb1
initialize calls initialize_boundaries
speedy calls initialize