land_model_init – SPEEDY.f90
land_model_init Subroutine
75 statements
Source File
public subroutine land_model_init()
Uses
input_output
boundaries
Initializes land model.
Arguments
None
Calls
Called by
Contents
None
Call graph
land_model_init calls forchk, load_boundary_file
load_boundary_file calls load_boundary_file_one_month_from_long, load_boundary_file_one_month_from_year, load_boundary_file_2d
load_boundary_file_one_month_from_long calls nf90_inq_varid, nf90_open, nf90_close, nf90_get_var
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_open, nf90_close, nf90_get_var
load_boundary_file_2d calls nf90_inq_varid, nf90_open, nf90_close, nf90_get_var
initialize_coupler calls land_model_init
initialize calls initialize_coupler
speedy calls initialize