laplacian – SPEEDY.f90
laplacian Function
5 statements
Source File
public function laplacian(input) result(output)
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: input(mx,nx)
Return Value complex (mx,nx)
Called by
Contents
None
Call graph
get_grid_point_tendencies calls laplacian
get_spectral_tendencies calls laplacian
get_tendencies calls get_grid_point_tendencies, get_spectral_tendencies
step calls get_tendencies
first_step calls step
speedy calls step, initialize
initialize calls first_step