legendre_inv – SPEEDY.f90
legendre_inv Function
23 statements
Source File
public function legendre_inv(input) result(output)
Computes inverse Legendre transformation.
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: input(2*mx,nx)
Input field
Return Value real (2*mx,il)
Output field
Called by
Contents
None
Call graph
spec_to_grid calls legendre_inv
spectral_truncation calls spec_to_grid
gen_sppt calls spec_to_grid
output calls spec_to_grid
get_grid_point_tendencies calls spec_to_grid
get_physical_tendencies calls spec_to_grid, gen_sppt
initialize_boundaries calls spectral_truncation
initialize_from_rest_state calls output
get_tendencies calls get_grid_point_tendencies
initialize_prognostics calls initialize_from_rest_state
initialize calls initialize_boundaries, initialize_prognostics, first_step
step calls get_tendencies
speedy calls initialize, step
first_step calls step