load_boundary_file_one_month_from_year – SPEEDY.f90
load_boundary_file_one_month_from_year Function
14 statements
Source File
private function load_boundary_file_one_month_from_year(file_name, field_name, month) result(field)
Loads the given 2D field at the given month from the given monthly boundary file.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
The NetCDF file to read from
character(len=*), intent(in) :: field_name
The field to read
integer, intent(in) :: month
The month to read
Return Value real, dimension(ix,il)
Calls
Called by
Contents
None
Call graph
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_get_var, nf90_open, nf90_close
load_boundary_file calls load_boundary_file_one_month_from_year
obs_ssta calls load_boundary_file
land_model_init calls load_boundary_file
initialize_boundaries calls load_boundary_file
sea_model_init calls load_boundary_file
initialize_coupler calls land_model_init, sea_model_init
initialize calls initialize_boundaries, initialize_coupler
speedy calls initialize