obs_ssta – SPEEDY.f90
obs_ssta Subroutine
11 statements
Source File
private subroutine obs_ssta()
Uses
date
input_output
boundaries
Arguments
None
Calls
Contents
None
Call graph
obs_ssta calls load_boundary_file
load_boundary_file calls load_boundary_file_one_month_from_long, load_boundary_file_one_month_from_year, load_boundary_file_2d
load_boundary_file_one_month_from_long calls nf90_inq_varid, nf90_open, nf90_close, nf90_get_var
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_open, nf90_close, nf90_get_var
load_boundary_file_2d calls nf90_inq_varid, nf90_open, nf90_close, nf90_get_var