output – SPEEDY.f90
output Subroutine
92 statements
Source File
public subroutine output(timestep, vor, div, t, ps, tr, phi)
Uses
geometry
physical_constants
date
spectral
Writes a snapshot of all prognostic variables to a NetCDF file.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: timestep
The time step that is being written
complex, intent(in) :: vor(mx,nx,kx,2)
Vorticity
complex, intent(in) :: div(mx,nx,kx,2)
Divergence
complex, intent(in) :: t(mx,nx,kx,2)
Temperature
complex, intent(in) :: ps(mx,nx,2)
log(normalized surface pressure)
complex, intent(in) :: tr(mx,nx,kx,2,ntr)
Tracers
complex, intent(in) :: phi(mx,nx,kx)
Geopotential
Calls
Called by
Contents
None
Call graph
output calls nf90_put_att, nf90_enddef, nf90_put_var, nf90_create, nf90_def_dim, spec_to_grid, nf90_close, nf90_def_var
spec_to_grid calls fourier_inv, legendre_inv
fourier_inv calls rfftb1
initialize_from_rest_state calls output
initialize_prognostics calls initialize_from_rest_state
initialize calls initialize_prognostics
speedy calls initialize