rfftb1 – SPEEDY.f90
rfftb1 Subroutine
61 statements
Source File
subroutine rfftb1(n, c, ch, wa, ifac)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real, intent(inout) :: c(*)
real, intent(inout) :: ch(*)
real, intent(inout) :: wa(*)
integer, intent(in) :: ifac(*)
Called by
Contents
None
Call graph
fourier_inv calls rfftb1
spec_to_grid calls fourier_inv
output calls spec_to_grid
get_physical_tendencies calls spec_to_grid, gen_sppt
get_grid_point_tendencies calls spec_to_grid
spectral_truncation calls spec_to_grid
gen_sppt calls spec_to_grid
initialize_boundaries calls spectral_truncation
get_tendencies calls get_grid_point_tendencies
initialize_from_rest_state calls output
step calls get_tendencies
initialize_prognostics calls initialize_from_rest_state
initialize calls initialize_boundaries, initialize_prognostics, first_step
first_step calls step
speedy calls step, initialize