run_sea_model – SPEEDY.f90
run_sea_model Subroutine
25 statements
Source File
private subroutine run_sea_model()
Uses
auxiliaries
mod_radcon
physical_constants
Arguments
None
Called by
Contents
None
Call graph
couple_sea_atm calls run_sea_model
initialize_coupler calls couple_sea_atm
couple_sea_land calls couple_sea_atm
speedy calls couple_sea_land, initialize
initialize calls initialize_coupler