run_land_model – SPEEDY.f90
run_land_model Subroutine
7 statements
Source File
private subroutine run_land_model()
Uses
auxiliaries
Integrates slab land-surface model for one day.
Arguments
None
Called by
Contents
None
Call graph
couple_land_atm calls run_land_model
initialize_coupler calls couple_land_atm
couple_sea_land calls couple_land_atm
speedy calls couple_sea_land, initialize
initialize calls initialize_coupler