sea_model_init – SPEEDY.f90
sea_model_init Subroutine
96 statements
Source File
public subroutine sea_model_init()
Uses
boundaries
date
geometry
input_output
Arguments
None
Calls
Called by
Contents
None
Call graph
sea_model_init calls load_boundary_file, forchk
load_boundary_file calls load_boundary_file_2d, load_boundary_file_one_month_from_year, load_boundary_file_one_month_from_long
load_boundary_file_2d calls nf90_get_var, nf90_inq_varid, nf90_open, nf90_close
load_boundary_file_one_month_from_year calls nf90_get_var, nf90_inq_varid, nf90_open, nf90_close
load_boundary_file_one_month_from_long calls nf90_get_var, nf90_inq_varid, nf90_open, nf90_close
initialize_coupler calls sea_model_init
initialize calls initialize_coupler
speedy calls initialize