set_forcing – SPEEDY.f90
set_forcing Subroutine
59 statements
Source File
public subroutine set_forcing(imode)
Uses
dynamical_constants
params
horizontal_diffusion
physical_constants
boundaries
surface_fluxes
date
land_model
sea_model
mod_radcon
shortwave_radiation
longwave_radiation
humidity
spectral
Compute forcing fields for the current date and correction terms for horizontal diffusion
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: imode
Mode -> 0 = initialization step, 1 = daily update
Calls
Called by
Contents
None
Call graph
set_forcing calls get_zonal_average_fields, setgam, grid_to_spec, set_orog_land_sfc_drag, get_qsat, radset
get_zonal_average_fields calls solar
grid_to_spec calls fourier_dir, legendre_dir
fourier_dir calls rfftf1, float
initialize calls set_forcing
speedy calls set_forcing, initialize