setgam – SPEEDY.f90
setgam Subroutine
11 statements
Source File
private subroutine setgam(gamlat)
Uses
dynamical_constants
params
physical_constants
Compute reference lapse rate as a function of latitude and date
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: gamlat(il)
The reference lapse rate
Called by
Contents
None
Call graph
set_forcing calls setgam
speedy calls set_forcing, initialize
initialize calls set_forcing