solar – SPEEDY.f90
solar Subroutine
28 statements
Source File
private subroutine solar(tyear, csol, topsr)
Uses
geometry
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: tyear
real, intent(in) :: csol
real, intent(inout) :: topsr(il)
Called by
Contents
None
Call graph
get_zonal_average_fields calls solar
set_forcing calls get_zonal_average_fields
speedy calls set_forcing, initialize
initialize calls set_forcing