spectral_truncation – SPEEDY.f90
spectral_truncation Subroutine
15 statements
Source File
private subroutine spectral_truncation(fg1, fg2)
Uses
spectral
Compute a spectrally-filtered grid-point field.
Arguments
Type Intent Optional Attributes Name
real, intent(inout) :: fg1(ix,il)
Original grid-point field
real, intent(inout) :: fg2(ix,il)
Filtered grid-point field
Calls
Called by
Contents
None
Call graph
spectral_truncation calls spec_to_grid, grid_to_spec
spec_to_grid calls fourier_inv, legendre_inv
grid_to_spec calls fourier_dir, legendre_dir
fourier_dir calls rfftf1, float
fourier_inv calls rfftb1
initialize_boundaries calls spectral_truncation
initialize calls initialize_boundaries
speedy calls initialize