spec_to_grid – SPEEDY.f90
spec_to_grid Function
10 statements
Source File
public function spec_to_grid(vorm, kcos) result(vorg)
Uses
legendre
fourier
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: vorm(mx,nx)
integer, intent(in) :: kcos
Return Value real (ix,il)
Calls
Called by
Contents
None
Call graph
spec_to_grid calls fourier_inv, legendre_inv
fourier_inv calls rfftb1
spectral_truncation calls spec_to_grid
get_grid_point_tendencies calls spec_to_grid
output calls spec_to_grid
get_physical_tendencies calls spec_to_grid, gen_sppt
gen_sppt calls spec_to_grid
initialize_from_rest_state calls output
get_tendencies calls get_grid_point_tendencies
initialize_boundaries calls spectral_truncation
initialize_prognostics calls initialize_from_rest_state
initialize calls initialize_boundaries, initialize_prognostics, first_step
step calls get_tendencies
speedy calls initialize, step
first_step calls step