step – SPEEDY.f90
step Subroutine
57 statements
Source File
public subroutine step(j1, j2, dt)
Uses
dynamical_constants
prognostics
horizontal_diffusion
tendencies
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j1
integer, intent(in) :: j2
real, intent(in) :: dt
Calls
Called by
Contents
None
Call graph
step calls step_field_2d, get_tendencies, do_horizontal_diffusion, step_field_3d
step_field_2d calls trunct
get_tendencies calls get_grid_point_tendencies, implicit_terms, get_spectral_tendencies
do_horizontal_diffusion calls do_horizontal_diffusion_3d, do_horizontal_diffusion_2d
step_field_3d calls step_field_2d
do_horizontal_diffusion_3d calls do_horizontal_diffusion_2d
get_grid_point_tendencies calls grid_to_spec, spec_to_grid, laplacian, get_geopotential
get_spectral_tendencies calls laplacian, get_geopotential
grid_to_spec calls fourier_dir, legendre_dir
spec_to_grid calls fourier_inv, legendre_inv
fourier_dir calls rfftf1, float
fourier_inv calls rfftb1
speedy calls step, initialize
first_step calls step
initialize calls first_step