trunct – SPEEDY.f90
trunct Subroutine
4 statements
Source File
public subroutine trunct(vor)
Arguments
Type Intent Optional Attributes Name
complex, intent(inout) :: vor(mx,nx)
Called by
Contents
None
Call graph
step_field_2d calls trunct
step calls step_field_2d, step_field_3d
step_field_3d calls step_field_2d
first_step calls step
speedy calls step, initialize
initialize calls first_step