vdspec – SPEEDY.f90
vdspec Subroutine
27 statements
Source File
public subroutine vdspec(ug, vg, vorm, divm, kcos)
Uses
geometry
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: ug(ix,il)
real, intent(in) :: vg(ix,il)
complex, intent(out) :: vorm(mx,nx)
complex, intent(out) :: divm(mx,nx)
integer, intent(in) :: kcos
Calls
Contents
None
Call graph
vdspec calls grid_to_spec, vds
grid_to_spec calls legendre_dir, fourier_dir
fourier_dir calls rfftf1, float