load_boundary_file – SPEEDY.f90
load_boundary_file Interface
5 statements
Source File
public interface load_boundary_file
Interface for reading boundary files.
Calls
Called by
Contents
Module Procedures
load_boundary_file_2d load_boundary_file_one_month_from_year load_boundary_file_one_month_from_long
Module Procedures
private function load_boundary_file_2d(file_name, field_name) result(field)
Loads the given 2D field from the given boundary file.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
The NetCDF file to read from
character(len=*), intent(in) :: field_name
The field to read
Return Value real, dimension(ix,il)
private function load_boundary_file_one_month_from_year(file_name, field_name, month) result(field)
Loads the given 2D field at the given month from the given monthly boundary file.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
The NetCDF file to read from
character(len=*), intent(in) :: field_name
The field to read
integer, intent(in) :: month
The month to read
Return Value real, dimension(ix,il)
private function load_boundary_file_one_month_from_long(file_name, field_name, month, length) result(field)
Loads the given 2D field at the given month from the given boundary file of a given length.
Read more…
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name
The NetCDF file to read from
character(len=*), intent(in) :: field_name
The field to read
integer, intent(in) :: month
The month to read
integer, intent(in) :: length
The total length of the file in number of months
Return Value real, dimension(ix,il)
Call graph
load_boundary_file calls load_boundary_file_one_month_from_long, load_boundary_file_2d, load_boundary_file_one_month_from_year
load_boundary_file_one_month_from_long calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
load_boundary_file_2d calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
load_boundary_file_one_month_from_year calls nf90_inq_varid, nf90_close, nf90_open, nf90_get_var
sea_model_init calls load_boundary_file
obs_ssta calls load_boundary_file
initialize_boundaries calls load_boundary_file
land_model_init calls load_boundary_file
initialize calls initialize_boundaries, initialize_coupler
initialize_coupler calls sea_model_init, land_model_init
speedy calls initialize