      INTEGER ISC
      PARAMETER (ISC=1)

      INTEGER NTRUN, MTRUN, IX, IY
      PARAMETER ( NTRUN=30, MTRUN=30, IX=96, IY=24 )   

      INTEGER NX, MX, MXNX, MX2, IL, NTRUN1, NXP, MXP, LMAX
      PARAMETER (NX=NTRUN+2, MX=MTRUN+1 , MXNX=MX*NX,MX2=2*MX)
      PARAMETER (IL=2*IY, NTRUN1=NTRUN+1 )
      PARAMETER (NXP=NX+1 , MXP=ISC*MTRUN+1, LMAX=MXP+NX-2 )
